# Generated by Django 5.1.6 on 2025-11-29 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=200)),
                ('building_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.building')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=100)),
                ('floor_area', models.PositiveIntegerField()),
                ('floor', models.CharField(max_length=20)),
                ('under_renovation', models.BooleanField(default=False)),
                ('agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agent')),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.building')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('participants_qty', models.PositiveIntegerField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('renovation_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'unique_together': {('agent_id', 'team_name')},
            },
        ),
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('amenity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.amenity')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venue')),
            ],
            options={
                'unique_together': {('venue_id', 'amenity_id')},
            },
        ),
    ]
