# Generated by Django 5.1.6 on 2025-11-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='venue_id',
        ),
    ]
