# Generated by Django 5.2.8 on 2025-11-29 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agent",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="amenity",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="renovation",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="venueamenity",
            options={"managed": False},
        ),
    ]
