# Generated by Django 5.1.6 on 2025-11-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.ManyToManyField(related_name='venues', through='home.VenueAmenity', to='home.amenity'),
        ),
        migrations.AlterUniqueTogether(
            name='venueamenity',
            unique_together={('venue', 'amenity')},
        ),
    ]
