# Generated by Django 5.1.6 on 2025-11-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_venue_amenities_alter_venueamenity_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_type',
            new_name='type',
        ),
    ]
