# Generated by Django 5.2.8 on 2025-11-29 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_agent_options_alter_amenity_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="agent",
            table="agent",
        ),
        migrations.AlterModelTable(
            name="amenity",
            table="amenity",
        ),
        migrations.AlterModelTable(
            name="building",
            table="building",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customer",
        ),
        migrations.AlterModelTable(
            name="renovation",
            table="renovation",
        ),
        migrations.AlterModelTable(
            name="reservation",
            table="reservation",
        ),
        migrations.AlterModelTable(
            name="team",
            table="team",
        ),
        migrations.AlterModelTable(
            name="venue",
            table="venue",
        ),
        migrations.AlterModelTable(
            name="venueamenity",
            table="venueamenity",
        ),
    ]
