# Generated by Django 5.1.6 on 2025-11-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_venue_type_venue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='venue_name',
        ),
    ]
