# Generated by Django 5.2.8 on 2025-11-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_agent_table_alter_amenity_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="venueamenity",
            table="venue_amenity",
        ),
        migrations.DeleteModel(
            name="Home",
        ),
    ]
