# Generated by Django 5.1.6 on 2025-11-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_venue_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='building',
            new_name='building_id',
        ),
    ]
