# Generated by Django 5.2.8 on 2025-11-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_venueamenity_table_delete_home"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="venueamenity",
            table="venueamenity",
        ),
    ]
