# Generated by Django 5.1.6 on 2025-11-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_building_venue_building_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='amenities',
        ),
    ]
