# Generated by Django 5.1.6 on 2025-11-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_venue_amenities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='name',
            new_name='agent_name',
        ),
    ]
