# Generated by Django 5.1.6 on 2025-11-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_name_agent_agent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_datetime',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_participants',
            new_name='participants_qty',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_datetime',
            new_name='start_date_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='venue',
            new_name='venue_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='agent',
        ),
    ]
