# Generated by Django 5.1.6 on 2025-11-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_customer_reservation_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueamenity',
            old_name='amenity',
            new_name='amenity_id',
        ),
        migrations.RenameField(
            model_name='venueamenity',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='venueamenity',
            old_name='venue',
            new_name='venue_id',
        ),
        migrations.AlterUniqueTogether(
            name='venueamenity',
            unique_together={('venue_id', 'amenity_id')},
        ),
    ]
