# Generated by Django 5.1.6 on 2025-11-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_amenity_venueamenity_amenity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('renovation_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agent')),
            ],
            options={
                'unique_together': {('agent_id', 'team_name')},
            },
        ),
    ]
