# Generated by Django 5.1.6 on 2025-11-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_renovation_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='name',
            new_name='building_name',
        ),
    ]
