# Generated by Django 5.1.6 on 2025-11-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_name_building_building_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='building_name',
            new_name='name',
        ),
    ]
