# Generated by Django 5.1.6 on 2025-11-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_name_building_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='building_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.building'),
        ),
        migrations.AddField(
            model_name='venue',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.agent'),
        ),
    ]
