# Generated by Django 5.1.6 on 2025-11-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_agent_building_id_venue_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='venue_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.venue'),
        ),
    ]
